# Generated by Django 4.2.7 on 2023-12-06 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tittle',
            new_name='title',
        ),
    ]
