# Generated by Django 4.2.7 on 2023-12-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_payment_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accpeted', 'Accpeted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Accpeted', 'Accpeted'), ('Cancel', 'Cancel'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
    ]
