# Generated by Django 4.2.7 on 2023-12-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='address',
            field=models.CharField(choices=[('Accpeted', 'Accpeted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Accpeted', 'Accpeted'), ('Cancel', 'Cancel'), ('Pending', 'Pending')], default='Pending', max_length=1000),
        ),
    ]
