# Generated by Django 4.2.7 on 2023-12-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_orderplaced_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='address',
            field=models.CharField(max_length=1000),
        ),
    ]
